### ISSUE TITLE
Cannot populate multiple portal-targets with one portal, vue components in portal don't replicate.

### ISSUE THREAD

**Issue by irjayjay** [LinusBorg/portal-vue#100]
I actually needed this mostly for replicating a component in different areas of the web page, meaning I need one portal that duplicates my own component to multiple portal-targets.

This is very useful, for example, when you have a cart icon on your e commerce site in different menus and contexts.

I got Portal Vue to replicate plain HTML multiple times, but if I render a component inside the portal tags, it only renders in the first portal-target.

I hope this makes sense, maybe I'm using it wrong, but I couldn't find anyone doing what I'm attempting to do.

Regards JJ

**Comment by LinusBorg** [comment]
If you use a normal spot on the portal, and then to render that slot content in multiple targets, the same vnode wo or be used in multiple places, which will certainly lead to problems when the slot content contains components. 

The Vue docs on render functions / slots explicitly say that vnodes should only be used once for this reason. 

However, portal-vue also supports scoped slots since version 1.3.0, and with those to should work fine. 

https://linusborg.github.io/portal-vue/#/guide?id=using-scoped-slots

**Comment by LinusBorg** [comment]
```html
<portal to="cart-icon">
  <!-- We don't "need" any props from the scoped slot, we just need its reusability -->
  <cartinIcon slot-scope="_"/> 
</portal>

<!--
Now you can use the following portal in as many places as you like.
I also added the `slim` prop to remove the wrapper element the target normally creates.
-->
<portal-parget name="cart-icon" slim />
```

If that *doesn't* work, I think I can make it work with a few tweaks, so please report back.

**Comment by LinusBorg** [comment]
I assume this question was answered.
