### ISSUE TITLE
Transferred components get reloaded at portal-target

### ISSUE THREAD

**Issue by Paul-Kijtapart** [LinusBorg/portal-vue#103]
Hello,

First of all, thank you for creating this component.
I am following your example from this post [https://forum.vuejs.org/t/how-to-create-a-single-file-component-for-full-printing/12839]

**What happens:**
With portal-vue, I am able to send content which includes static and some chart components from dashboard container. Components are transferred from <portal> to <portal-target> correctly.

**Issues:**
However, Transferred components get reloaded at portal-target
(1) when content gets sent to the portal-target, each chart component get re-created (send ajax => get data => re-render chart). 

(2) after finish printing, I set print=false, to close the print preview. With print=false, The content in portal will be re-loaded (all chart components get re-loaded)

**Questions:**
I am wondering if it will be possible to transfer content from <portal> to <portal-target-> without components inside the content re-loading (i.e.. prevent the chart components from re-loading when it gets transfer to print-portal-target, and also when it gets transferred back on completePrint)

Any help is appreciated.

**Comment by LinusBorg** [comment]
I don't think that's possible. 

This plugin doesn't transfer the finished DOM elements? It transfers the virtual DOm nodes, and then vue renders DOM for those vnodes. 

When you enable/disable the portal and the vnodes are rendered in a different place, the original component can't be re-used because different, new dom will be created.
