### ISSUE TITLE
The ref of an element inside a portal will be lost if that component is rendered inside a <component>

### ISSUE THREAD

**Issue by decademoon** [LinusBorg/portal-vue#106]
If you are using `<component :is="...">` to render CompA and then change `is` to CompB, any refs in CompB inside the portal will not be set.

It's kind of hard to explain, I have a [fiddle](http://jsfiddle.net/df4Lnuw6/188/) which demonstrates this issue.

**Comment by LinusBorg** [comment]
Thanks for reporting.

As a quick first analysis I can say that this probably is due to a mismatch in Vue's patch algorithm - both `compa` and `compb` essentially produce the same virtualdom, so Vue thinks it can just re-use the `<span>` that it created, but due to some effect the portal'ing of vdom nodes has, this messes things up.

A workaround is to add a unique key:

http://jsfiddle.net/y9bgt4zf/1/

I will have a look if I can improve this situation in the portal, maybe add a different key to all top-level vnodes, derrived from the source portal's name or something.

If that doesn't work, I'll document this asa caveat.

FYI, I won't find much time to work acively on this lib until mid-march, so thanks in advance for your patience.

**Comment by LinusBorg** [comment]
@decademoon I took another look at this, and as far as I can tell, the fiddle works now. 

If that's indeed the case, it seems a change in Vue or portal-vue solved this issue as a side-effect.

Can you verify on your end?

**Comment by nodegin** [comment]
VDom refs (custom components) seems broken after portal

**Comment by iambumblehead** [comment]
I'm using vue 2.5.17 and portal-vue 1.5.1 and can confirm that this is an issue there.

I'm using single file components with scoped styles to render modals to a portal target. Here the problem manifests by applying previous modal styles to subsequent modals. For example, if a green-background modal is rendered then a red-background modal is rendered the 'red' modal appears with the green background.

**Comment by LinusBorg** [comment]
@iambumblehead This issue is about refs, and your description sounds like something different.

Please open a fresh issue with a reproduction on jsfiddle or similar so I can check out what's going on.

I'll close this issue as OP never reported back.
