### ISSUE TITLE
Portals vs Scoped Slots

### ISSUE THREAD

**Issue by nateajohnson** [LinusBorg/portal-vue#123]
I'm trying to wrap my head around portals. If this has already been explained somewhere, please post a link. Can someone explain when to use portals rather than Vue's built in scoped slots? They seem similar, but I think I am missing something.

Thanks!

**Comment by LinusBorg** [comment]
Well, with slots - scoped or unscoped - you pass a "piece of template" from a parent component to a  child component - so it will render somewhere in the child DOM tree of the parent component.

Portals are meant to move render the "template" that you passed to it in a totally different place in the DOM - namely where the portal-target is rendered. This is simply not possible with (scoped or unscoped) slots.

In fact, `<portal>`uses slots (both scoped and unscoped) to receive the "template" from its parent component just like a normal component. But instead of rendering that slot content inside of its own template, it renders nothing, and pases the content to the defined `<portal-target>`.

Does that make it clearer? Have you checked out the examples in the docs, e.g. this CodePen?

https://codepen.io/LinusBorg/pen/xdQZqa

**Comment by nateajohnson** [comment]
Thanks @LinusBorg, and yes, that does make it clearer. I think portals will solve a few issues in our projects where the CSS was taking over where it wan't intended to, particularly in our modals. 

Nate

**Comment by LinusBorg** [comment]
Moving modals, dropdown menus, snackbars and similar components to the end of the body is a common use case for portal-vue, indeed.
