### ISSUE TITLE
JS Hooks transitions?

### ISSUE THREAD

**Issue by thariddler** [LinusBorg/portal-vue#148]
Hi there! Portal is awesome, but I can't find how can I use them with JS Hooks? Please don't tell me this is impossible :smile: 

```html
<portal-target name="modals" :transition="{ name: 'fade'}"></portal-target>
```

This works great, but I want JS animations instead. And I need to use Portal API for transitions, since I am reusing same target with multiple modals and it is impossible to make it work other way (I didn't find the solution, since transition works only on Enter, if I am using native Vue transition tags).

Thanks!

**Comment by LinusBorg** [comment]
https://linusborg.github.io/portal-vue/#/docs/portal-target?id=transitionevents

**Comment by iamrddlr** [comment]
@LinusBorg thanks Linus, but why then this example has both, CSS and JS transitions?

```html
<portal-target
  name="dest"
  :transition="{name: 'fade'}"
  :transition-events="{ enter: handleEnter, leave: handleLeave }">
```

**Comment by LinusBorg** [comment]
`transition` gets the props you would passes to `<transition>` 
`transitionEvents` gets the event handlers. 

If you want yo angle everything with event hooks, then the only transition *prop* is the name, just like the example shows.

**Comment by iamrddlr** [comment]
@LinusBorg thanks for reply. Although it's still unclear for me, unfortunately. For example, I want to handle everything in JS, but I still need to point at `fade` transition? Even if it will not fade at all? Don't get it, sorry.

**Comment by LinusBorg** [comment]
You probably don't have to provide a name, no. 

As a suggestion: you give me an example of a normal Vue `<transition>` component with all the props and events you want on it, and I will show you how to apply the same to `<portal-target.>`

**Comment by iamrddlr** [comment]
Great, please give me a day, I'll made an example tomorrow. Really appreciate it.

**Comment by iamrddlr** [comment]
@LinusBorg hello, Linus. 

I made an example. There I have fairly complex transitions on modal:

1. Modal wrapper transition, that is right now is simple fade (and I want to make in scale, for example). Right now it's CSS, but I want this transition to be handled with JS. Why? See next.

2. Next I have transition on modal content itself. It is handled inside this Modal itself. It's completely different animation. 

3. Last enter transition is on elements that's inside modal content. They stagger in this example.

4. The interesting part (and why I created this issue) is happening when you close the modal. As you see, my Modal component blocks scroll by adding CSS styles to root elements. My issue, is if I have transition #1 in this list, to prevent jerking I need to set timeout that is equal to my transition #1 timing function. This way first my leave animation completes and only after I will remove CSS styles that's blocking scroll. As you see this is very inconvenient, to have this timing in CSS and in Modal itself. So I want to use common variable for it, that's why I want to make Portal to work with JS transition.

Hope this explanation is clear (not native speaker). If not, please ask, I will provide another explanation. And thanks for reading already. 

https://codesandbox.io/s/26x07yl0j

**Comment by LinusBorg** [comment]
Thanks.
So the transition that you want to apply to the target isn't really fleshed out yet, right?

```html
<portal-target name="modals" :transition="{ name: 'fade'}"></portal-target>
```
But let's just take this one:
```
      <transition @enter="enterModal" @leave="leaveModal" :css="false">
        <div v-if="modal" class="modal">
          <div class="modal-controls">
            <slot name="close-button" :close="close"></slot>
          </div>
        </div>
      </transition>
```
on the portal-target, it would look like this:
```html
<portal-target name="modals" 
  :transition="{ css: false }"
  :transition-events="{
    enter: enterModal,
    leave: leaveModal
  }"
>
</portal-target>
```
