### ISSUE TITLE
Refs seems to get lost?

### ISSUE THREAD

**Issue by sebmor** [LinusBorg/portal-vue#154]
I have this example based on a real use case I'm trying to achieve.

https://codesandbox.io/s/k58v892r5r

These are 2 modals who use the same portal-target. 
I think there is a couple of things wrong here. First try to open the modals from the "main navigation" a few times, they will stop working.

Also when I open one, then open another one, and then close it (click anywhere in the modal), it will revert back to the old one.
I would think the default behaviour of vue-portal is that it replaces the current portal. If you check the DOM code it does as well. But still it seems to keep it in memory so after you remove one, it will revert to the old one. 

I also tried to empty the portal by using Wormhole.close with force as described in the docs, but that doesnt seem to do much?

Is there a recommended way to reliably replace the portals content and not add up a history of nodes? That would probably simplify everything?

**Comment by LinusBorg** [comment]
> Also when I open one, then open another one, and then close it (click anywhere in the modal), it will revert back to the old one.
I would think the default behaviour of vue-portal is that it replaces the current portal. If you check the DOM code it does as well. But still it seems to keep it in memory so after you remove one, it will revert to the old one.

I understand that expectation, but it's wrong.

to support the `multiple` prop on the portal-target, the wormhole in the middle collects all incoming content and "queues" it. And 

* if  the portal-target has `multiple` set, it can display all of the content.
* if it hasn't, it will only show the first "item" saved in the wormhole.

And since you don't actually close your modals, but open both, and then close one, the "older" modal becomes the first item in line as soon as the second modal was closed.

In other words: Content is only removed if you 

a. destroy the `<portal>` that sent it (e.g. with v-if="false") or 
b. disable the `<portal>` with the `disabled` prop.

This also explains why this happens:

> First try to open the modals from the "main navigation" a few times, they will stop working.

They don't "stop working". it's just that when you open an already "opened" modal for a second time, nothing changed. `showModal` was true before and it true after you clicked "open Login" for a second time, so nothing was re-rendered, and so the `<portal>` didn't (and couldn't) send an update to the wormhole (& target).

So your problems come from your pattern of 

1. calling a method on the modal instance to show it, and 
2. not closing it when you want it to be closed, instead trying to rely on portal-vue overwriting its content.

Generally I think using refs and methods like that is a bad pattern. I set props to make the modal open and keep it open until I set the prop back to `false`. That's very transparent - as long as the data in the parent is `true`, the modal will show. When it's false, it's gone again.

Relying on method calls instead hides the state from the parent and makes the process intransparent.

Here's a reimplementation of your modal concept using only props and events.

https://codesandbox.io/s/yjmk2l3v81

The upside is that you can now open your devtools and inspect what all the props are and which component sends which state upwards to make a modal close or switch to another.
