### ISSUE TITLE
Add back Wormhole.hasContentFor

### ISSUE THREAD

**Issue by bbugh** [LinusBorg/portal-vue#194]
The Wormhole docs say `hasContentFor` will let me check if a portal has content. TypeScript is reporting that this method doesn't exist or isn't exported. It seems like maybe it's not exported for TypeScript? This is really important for my use case, because I need to wrap the portal output in some styles.

Here's a simplified example of what I need. It's critical to our setup, and the reason I'm evaluating portal-vue is because slots and `router-view` are both failing in our scenario. `portal-vue` is perfect, except I need to know if content has been defined.

Here's a simplified example:

```html
<!-- this shouldn't appear at all if there's no content because it breaks the page layout -->
<div v-if="hasSidebarPortalContent">
  <div class="something for responsive">
    <portal-target name="sidebar" /> 
  </div>
</div>
```
```javascript
computed () {
  hasSidebarPortalContent () {
    return Wormhole.hasContentFor('sidebar')
  }
}
```

Is this just missing from the type export or is there some different way to do this?

**Comment by LinusBorg** [comment]
😩

That's one of the few APIs I dropped for 2.0 since I *never* came across anyone using them. Which is why you won't find them in the docs for 2.0 on portal-vue.linusb.org. Did you look at old docs perhaps?

I can consider adding it back in, now that I have finally seen a use case for it. 😅

But might take a few days.

As a workaround, you could use this for now:

```javascript
return !!Wormhole.transports[sidebar].length
```

`Wormhole.transports` is not strictly public API but won't change in this major, I can promise that.

**Comment by bbugh** [comment]
Haha, oh no! I see now that you just removed it a few days ago. I hadn't seen the 2.0 upgrading guide until searching google for the method name. I'm surprised this hasn't come up before! Wrapping things like this in some kind of containers seems like a common use case to me.  Thank you for the quick response and the re-add, and the workaround until 2.1 is released. (and all the hard work)
