### ISSUE TITLE
Portal-Target outside of app not working

### ISSUE THREAD

**Issue by herteleo** [LinusBorg/portal-vue#198]
Tested with: 2.0.0 & 2.1.0

I try to use the `portal-target` outside of the app but it receives no content. I made an example with the code mentioned in the docs and even this is not working: https://codepen.io/herteleo/pen/OGOJaX

When I move the target into the app it's working properly.

**Comment by tmorehouse** [comment]
that is because the app isn't compiling custom components outside of the app. It is pure HTML, and Vue is only looking at what is inside the app.

Either move the portal-target to be the last element inside your app, or use MountingPortal to create the portal-target for you.  Setting `mount-o="body"` and `:append="true"`

**Comment by herteleo** [comment]
Thanks for the fast reply! After your message I found the [advanced usage](https://portal-vue.linusb.org/guide/advanced.html#rendering-outside-of-the-vue-app) section where this is documented. I was misled by the documentation under [Use Cases](https://portal-vue.linusb.org/guide/getting-started.html#use-cases) where it looks like that the usage syntax inside and outside the app is the same.

**Comment by towry** [comment]
![截屏2020-07-02 10 38 46](https://user-images.githubusercontent.com/8279858/86310340-64a28700-bc50-11ea-8eef-4c6dc83a9ac9.png)


confusing
