### ISSUE TITLE
vue-common used instead of vue-esm

### ISSUE THREAD

**Issue by djixadin** [LinusBorg/portal-vue#264]
Hi, 

portal-vue v2.1.6
vue 2.6.10
webpack 4.41.0

when i import it i can see in my vendors file that common version is used

/***/ "./node_modules/portal-vue/dist/portal-vue.common.js":
/*!***********************************************************!*\
  !*** ./node_modules/portal-vue/dist/portal-vue.common.js ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__)

i import it like this like it states here https://portal-vue.linusb.org/guide/installation.html#builds

```
import PortalVue from 'portal-vue';
Vue.use(PortalVue);
```

Regards

**Comment by Hanziness** [comment]
I've run into this one, too. I've tried to create a project with Nuxt and Electron (template: https://github.com/michalzaq12/electron-nuxt ) and just by having the line
```js
import { PortalTarget } from 'portal-vue'
```
or basically any `portal-vue` import (including the Nuxt module setup) will cause my app to display the "You are running Vue in development mode." message *twice*, which AFAIK means I have two Vue instances (this also causes further problems, like a bunch of Vue warnings popping up about `$attrs` being read-only etc.). I've also checked that the second message comes from `vue.runtime.COMMON.dev.js` being referenced using an absolute path (capitalization is only for emphasis) while everything is using the ES `import` syntax in my code, thus Vue is loaded from `vue.runtime.esm[.dev].js`.

Just by removing all `vue-portal` imports (also removing the Nuxt module line) fixes this. It's also quite possible that I'm not using Portal-Vue properly, but I cannot use Portal-Vue without two Vue instances as of now (and I'd expect every `import` to cause the ESM version of Vue to be used) :/

I'm not sure how much a Webpack problem this is, since directly importing `portal-vue/dist/portal-vue.esm.js` throws an "Unexpected identifier" error because it's somehow transpiled into a `require()` call - that I found out from the stack trace.

**Comment by LinusBorg** [comment]
Yeah that's unfortunately a weid situation in the current ecosystem that I'm unsure how to resolve:

Webpack prioritizes the `"browser"` field over the `"module"` field, for some weird historic reason.

The general recommendation seems to be to have the "main" refer to the commonjs and have no "browser" field, but then where to put the UMD?

Or I drop the commonjs build and provide only UMD and ESM. Would be a breaking change though, I'd think.

For the moment, you could use a [webpack alias](https://webpack.js.org/configuration/resolve/#resolvealias) to make `portal-vue` load the esm build:

```javascript
{
  alias: {
    'portal-vue': path.join(path.dirname(require.resolve('portal-vue')), 'portal-vue.esm.js')
  }
}
```
