### ISSUE TITLE
Using without target (appending to document.body by default)

### ISSUE THREAD

**Issue by ivryb** [LinusBorg/portal-vue#29]
Hi!
I got many different modals in different Vue-components and it is really boring to create a coincident `<portal-target>` for each of them. It is a quite common case, as I know.
Allowing to use `<portal>` without `to` prop and appending its content directly before `</body>` by default then would be a great solution.

**Comment by tmorehouse** [comment]
This would be definitely handy, having the target element automatically created and appended to the body if the  `to` and `targetEl` props are empty..

**Comment by LinusBorg** [comment]
About your situation:

* If only one modal is shown at once, you can re-use one `<portal-target>` for all modals. They don't all need their own. That should work for most cases.
* I'm currently working on a feature to use moltiple sources at the same time for one target in #26.

Between these two things, you probably won't need more than two or three targets for a lot of modals etc.

Furthermore, I think I want to keep a `to` mandatory because a name is requried for the virutalDOM transfer queue to work properly, and I don't want to rely on some `__default` naming for situations where non would be provided.

**Comment by ivryb** [comment]
I missed the fact that I can use one `portal-target` for all `portal`'s...
Thank you!

**Comment by LinusBorg** [comment]
I will close this because I don'T think that this feature is necessary. I also plan on making it possible to send content form multiple portals to the same target *at the same time* (see #26), which would further improve the flexibility when you have variable content.

That will have to wait until 1.1 because the internal changes will be significant and I want to nail the API just right.

**Comment by vq0599** [comment]
How to append to document.body in a component library (not application)?
we can't access root when work in library project.

**Comment by LinusBorg** [comment]
Likely like this:

https://portal-vue.linusb.org/guide/advanced.html#rendering-outside-of-the-vue-app

**Comment by vq0599** [comment]
thanks
