### ISSUE TITLE
Importing as an ES Module in the browser

### ISSUE THREAD

**Issue by lsimichael** [LinusBorg/portal-vue#325]
I would like to start importing ES Modules directly into the browser from a CDN, without a build step. I can do this for Vuex and Vue Router, but I am not able to do this with Portal Vue, as the 'vue' import is missing.

The file endings for Vuex and Vue Router are `.esm.browser.min.js` -- could there be a similar ESM browser build for Portal Vue?

**Comment by LinusBorg** [comment]
> I am not able to do this with Portal Vue, as the 'vue' import is missing.

I'm not entirely sure what you are referring to here, but have a suspicion. 

The esm build of portal-vue does:

```js
import Vue from 'vue'
```

Do you see that as a problem? Because that's what the import is supposed to look like. VueRouter doesn't have it because it doesn't need direct access to the Vue constructor. PortalVue does, so there isn't really any way around that.

The core of the issue is that by default, a normal web server won't map a request for `vue` to the node_modules folder.

Thats something to be solved by the server, though. The esm build is valid.

You might want to look into solutions such as [Vite](https://vitejs.dev) to use native es modules in the browser during development.

**Comment by lsimichael** [comment]
Closing as this sounds like this isn't something that will be supported.

For anyone else trying to do this without a build step, I'm just copy/pasting the file and updating the 'vue' reference at the top.
