### ISSUE TITLE
Portal via target-el breaks when router-link is inside

### ISSUE THREAD

**Issue by simplesmiler** [LinusBorg/portal-vue#34]
Repro: https://jsfiddle.net/14dtfh51/21/

Presumably, this happens because the resulting `portal-target` instance has no parent, so it can not reach the root instance where the router is defined.

Works fine with normal portals (non-`target-el`).

**Comment by LinusBorg** [comment]
Good catch. I think passing the router along to the PortalTarget instance should be enough.

**Comment by LinusBorg** [comment]
> Presumably, this happens because the resulting portal-target instance has no parent, so it can not reach the root instance where the router is defined.

Seems I didn't thoroughly read this - that's correct, just checked the source.

So fixing this should fix 3#5 as well.

**Comment by simplesmiler** [comment]
You could set `parent: this` when creating a remote `portal-target` (with `this` being the portal itself). But it would also change where exactly the resulting `portal-target` will appear in the devtools. Currently it appears as a second root, but with `parent: this` it would appear under the corresponding portal. I don't know which way is more correct.

**Comment by LinusBorg** [comment]
>  I don't know which way is more correct.

That's a tricky question.

* When you mount to an element within the scope of the same root instance, `this` might be better
* When you mount into the scope of a different root instance, we would have to pick that one.
* When you mount to an element outside of any root instance's scope, then no parent would be the right thing.

A possible way would be to look for `e.__vue__` in the target's parent node tree and

* if none exists, leave `parent` blank
* if one exists, and it is the same as the source's `$root`, then use the instance we found with `el.__vue__`
* otherwise, use `this`

Will have to play witht these possibilities.

Genereally though, one could argue that `this` is never really wrong, as `this` mounted the portal-target ...

**Comment by LinusBorg** [comment]
On second thought, only with `{parent: this}` will `$router` work and refer to the source's router instance, so this might be the only sensible option.
