### ISSUE TITLE
Vue.use(PortalVue) causing event emissions to fail

### ISSUE THREAD

**Issue by bartboy011** [LinusBorg/portal-vue#47]
Essentially, as soon as I import PortalVue and add it to Vue, any instance of `this.$emit('event')` stops firing. However, it doesn't affect the `eventBus` I've set up. I'm using Webpack 2 through the Webpacker gem for rails. Here's some code:

```javascript
// vue-config.js

import Vue from 'vue/dist/vue.esm'

import VeeValidate from 'vee-validate'
Vue.use(VeeValidate)

import PortalVue from 'portal-vue'
Vue.use(PortalVue)

require('vue-apparate')
VueApparate.init(Vue)

window.eventBus = new Vue()

// app.js

import Vue from 'vue/dist/vue.esm'
import components from './pages/pages'

import '@/assets/css/frontend.scss'
require('@/scripts/require-all') // requires all files in /scripts, which includes vue-config.js

new Vue({
  el: '#app',
  components
})
```

Actual usage of PortalVue is irrelevant. If I comment out `Vue.use(PortalVue)` the problem immediately dissipates. Here's an example usage:

```javascript
<template>
<div class="modal-container">
  <div class="modal" @click="close">
    <slot></slot>
  </div>
</div>
</template>

<script>
export default {
  name: "VueModal",
  methods: {
    close() {
      this.$emit('close')
    }
  }
}
</script>
```
Through some console.log debugging, I know that the method `close` is firing, but VueDevtools confirms that no events are being emitted. Additionally, in the console, without PortalVue I get the typical dev environment warning:

![screen shot 2017-05-23 at 10 34 20 am](https://cloud.githubusercontent.com/assets/20690809/26362402/6d905a86-3fa3-11e7-8749-c27dd4abd0ee.png)

But once I add PortalVue I get two of these warnings:

![screen shot 2017-05-23 at 10 35 00 am](https://cloud.githubusercontent.com/assets/20690809/26362427/822a1586-3fa3-11e7-8bf2-449c50cdab8c.png)

Any thoughts what may be causing this?

**Comment by LinusBorg** [comment]
`import Vue from 'vue/dist/vue.esm'`

You should never import Vue this way when using webpack - instead, use an alias in the webpack config (this is not related to PortalVue btw). 

See here: https://github.com/vuejs/vue/blob/dev/dist/README.md#webpack

Otherwise, during develpoment you will end up with 2 different versions of Vue loaded in the browser, because vue-loader/hot-reloading refers to vue always as `import Vue from 'vue'`, which is pointing to `vue.runtime.esm.js` by default.

Please try this first and report back if that doesn't fix your problem.

If the problem persists, it would be helpful to have an actual reproduction of the issue, preferably in a small repository that is stripped down to only demonstrate the problem.

**Comment by bartboy011** [comment]
Awesome, thank you. The [Webpacker gem](https://github.com/rails/webpacker) defaults to this implementation, I'll go issue a pull request over there to clean that up. I'll give that a try and if there are no continuing issues I'll close the issue.

**Comment by LinusBorg** [comment]
Great!
