### ISSUE TITLE
A portal should not force to use a suit

### ISSUE THREAD

**Issue by miljan-aleksic** [LinusBorg/portal-vue#68]
Hi!

by default the ported code is wrapped with `vue-portal-target`div, which I saw in the source code allows a lot of customizations but is actually an issue. Example, when used to build a menu which items are expected to be on first level `<li /><li />...` and not like `<div><li/><li/></div>`.

I believe the portal target is placed in a well know safe place and doesn't require any protection suit :)

**Comment by LinusBorg** [comment]
(for anyone reading, this started in a comment in #66)

I think in #66 I misunderstood you - I thought you meant the empty div created when there's nothing to show (but I probably should get rid of that as well). 

For the example you describe, there is actually an option: `slim`. However, since Vue requires components to have a single root node, this only works if the content you send to the target consists of one vnode only (and arbitrary children, of course)

https://linusborg.github.io/portal-vue/#/docs/portal-target?id=slim

**Comment by miljan-aleksic** [comment]
You are right, I confused the functional component hability to render multiple nodes... I guess we are stuck with the suit for now :)
